--- #YAML:1.0
name: Data-Dumper-Names
version: 0.02
author:
  - "Curtis <ovid@cpan.org>"
abstract: "Dump variables with names (no source filter)"
license: perl
generated_by: Module::Build version 0.2704, without YAML.pm
